name: Commitlint

on:
  pull_request:
    types: [assigned, opened, synchronize, edited, reopened]

jobs:
  lint-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Fetch main branch
        run: git fetch origin main

      - name: Install dependencies
        run: npm install

      - name: Run Commitlint with custom error message
        run: |
          # Fetch all commit messages from the pull request
          commit_messages=$(git log --format=%s origin/main..HEAD)
          
          # Loop through commit messages and validate them
          while IFS= read -r commit_message; do
            # Skip merge commits
            if [[ $commit_message == Merge* ]]; then
              echo "Skipping merge commit: '$commit_message'"
              continue
            fi

            # Run commitlint on the commit message
            if ! echo "$commit_message" | npx commitlint; then
              echo "Error: Invalid commit message format for commit: '$commit_message'"
              echo "Expected commit message format:"
              echo "  <type>(TEAM-<jira-ticket-number>): <description>"
              echo "Example: feat(TEAM-1234): add login functionality"
              exit 1
            fi
          done <<< "$commit_messages"
